name: Pipeline
on:
  push:
    branches:
      - master
      - setup-phpstan

  pull_request:
    branches:
      - master

jobs:
  testsuite:
    name: Testes Automatizados
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0']

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, mysql, zlib, dom, openssl, soap, json, simplexml, libxml

      - name: checkout
        uses: actions/checkout@v2

      - name: Set phpunit version
        if: matrix.php-version == '7.0' || matrix.php-version == '7.1'
        run: composer require "phpunit/phpunit:^7.5" -W --dev

      - name: Composer Install
        run: |
          composer install --no-progress -o --no-ansi --no-interaction

      - name: Análises estáticas
        if: matrix.php-version != '7.0' && matrix.php-version != '7.1'
        run: |
          composer stan

      - name: Rodando PHPUnit
        run: |
          composer test
